# Generated by Django 2.1.15 on 2020-05-06 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200506_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
