# Generated by Django 2.1.15 on 2020-05-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_order_id',
            field=models.CharField(default=1000, max_length=100),
        ),
    ]
