# Generated by Django 2.1.15 on 2020-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_subscription_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='razorpay_order_id',
            field=models.CharField(max_length=100),
        ),
    ]
